# Generated by Django 3.2.7 on 2021-09-16 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.characters')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.quotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritequotes',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favoritequotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteCharacters',
        ),
        migrations.DeleteModel(
            name='FavoriteQuotes',
        ),
    ]
