# Generated by Django 3.2.7 on 2021-09-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210916_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.characters'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.quotes'),
        ),
    ]
